#pragma once
#include <hipblas.h>
#define CUBLAS_COMPUTE_16F HIPBLAS_COMPUTE_16F
#define CUBLAS_COMPUTE_16F_PEDANTIC HIPBLAS_COMPUTE_16F_PEDANTIC
#define CUBLAS_COMPUTE_32F HIPBLAS_COMPUTE_32F
#define CUBLAS_COMPUTE_32F_FAST_16BF HIPBLAS_COMPUTE_32F_FAST_16BF
#define CUBLAS_COMPUTE_32F_FAST_16F HIPBLAS_COMPUTE_32F_FAST_16F
#define CUBLAS_COMPUTE_32F_FAST_TF32 HIPBLAS_COMPUTE_32F_FAST_TF32
#define CUBLAS_COMPUTE_32F_PEDANTIC HIPBLAS_COMPUTE_32F_PEDANTIC
#define CUBLAS_COMPUTE_32I HIPBLAS_COMPUTE_32I
#define CUBLAS_COMPUTE_32I_PEDANTIC HIPBLAS_COMPUTE_32I_PEDANTIC
#define CUBLAS_COMPUTE_64F HIPBLAS_COMPUTE_64F
#define CUBLAS_COMPUTE_64F_PEDANTIC HIPBLAS_COMPUTE_64F_PEDANTIC
#define CUBLAS_DEFAULT_MATH HIPBLAS_DEFAULT_MATH
#define CUBLAS_DIAG_NON_UNIT HIPBLAS_DIAG_NON_UNIT
#define CUBLAS_DIAG_UNIT HIPBLAS_DIAG_UNIT
#define CUBLAS_FILL_MODE_FULL HIPBLAS_FILL_MODE_FULL
#define CUBLAS_FILL_MODE_LOWER HIPBLAS_FILL_MODE_LOWER
#define CUBLAS_FILL_MODE_UPPER HIPBLAS_FILL_MODE_UPPER
#define CUBLAS_GEMM_ALGO0 HIPBLAS_GEMM_ALGO0
#define CUBLAS_GEMM_ALGO0_TENSOR_OP HIPBLAS_GEMM_ALGO0_TENSOR_OP
#define CUBLAS_GEMM_ALGO1 HIPBLAS_GEMM_ALGO1
#define CUBLAS_GEMM_ALGO10 HIPBLAS_GEMM_ALGO10
#define CUBLAS_GEMM_ALGO10_TENSOR_OP HIPBLAS_GEMM_ALGO10_TENSOR_OP
#define CUBLAS_GEMM_ALGO11 HIPBLAS_GEMM_ALGO11
#define CUBLAS_GEMM_ALGO11_TENSOR_OP HIPBLAS_GEMM_ALGO11_TENSOR_OP
#define CUBLAS_GEMM_ALGO12 HIPBLAS_GEMM_ALGO12
#define CUBLAS_GEMM_ALGO12_TENSOR_OP HIPBLAS_GEMM_ALGO12_TENSOR_OP
#define CUBLAS_GEMM_ALGO13 HIPBLAS_GEMM_ALGO13
#define CUBLAS_GEMM_ALGO13_TENSOR_OP HIPBLAS_GEMM_ALGO13_TENSOR_OP
#define CUBLAS_GEMM_ALGO14 HIPBLAS_GEMM_ALGO14
#define CUBLAS_GEMM_ALGO14_TENSOR_OP HIPBLAS_GEMM_ALGO14_TENSOR_OP
#define CUBLAS_GEMM_ALGO15 HIPBLAS_GEMM_ALGO15
#define CUBLAS_GEMM_ALGO15_TENSOR_OP HIPBLAS_GEMM_ALGO15_TENSOR_OP
#define CUBLAS_GEMM_ALGO16 HIPBLAS_GEMM_ALGO16
#define CUBLAS_GEMM_ALGO17 HIPBLAS_GEMM_ALGO17
#define CUBLAS_GEMM_ALGO18 HIPBLAS_GEMM_ALGO18
#define CUBLAS_GEMM_ALGO19 HIPBLAS_GEMM_ALGO19
#define CUBLAS_GEMM_ALGO1_TENSOR_OP HIPBLAS_GEMM_ALGO1_TENSOR_OP
#define CUBLAS_GEMM_ALGO2 HIPBLAS_GEMM_ALGO2
#define CUBLAS_GEMM_ALGO20 HIPBLAS_GEMM_ALGO20
#define CUBLAS_GEMM_ALGO21 HIPBLAS_GEMM_ALGO21
#define CUBLAS_GEMM_ALGO22 HIPBLAS_GEMM_ALGO22
#define CUBLAS_GEMM_ALGO23 HIPBLAS_GEMM_ALGO23
#define CUBLAS_GEMM_ALGO2_TENSOR_OP HIPBLAS_GEMM_ALGO2_TENSOR_OP
#define CUBLAS_GEMM_ALGO3 HIPBLAS_GEMM_ALGO3
#define CUBLAS_GEMM_ALGO3_TENSOR_OP HIPBLAS_GEMM_ALGO3_TENSOR_OP
#define CUBLAS_GEMM_ALGO4 HIPBLAS_GEMM_ALGO4
#define CUBLAS_GEMM_ALGO4_TENSOR_OP HIPBLAS_GEMM_ALGO4_TENSOR_OP
#define CUBLAS_GEMM_ALGO5 HIPBLAS_GEMM_ALGO5
#define CUBLAS_GEMM_ALGO5_TENSOR_OP HIPBLAS_GEMM_ALGO5_TENSOR_OP
#define CUBLAS_GEMM_ALGO6 HIPBLAS_GEMM_ALGO6
#define CUBLAS_GEMM_ALGO6_TENSOR_OP HIPBLAS_GEMM_ALGO6_TENSOR_OP
#define CUBLAS_GEMM_ALGO7 HIPBLAS_GEMM_ALGO7
#define CUBLAS_GEMM_ALGO7_TENSOR_OP HIPBLAS_GEMM_ALGO7_TENSOR_OP
#define CUBLAS_GEMM_ALGO8 HIPBLAS_GEMM_ALGO8
#define CUBLAS_GEMM_ALGO8_TENSOR_OP HIPBLAS_GEMM_ALGO8_TENSOR_OP
#define CUBLAS_GEMM_ALGO9 HIPBLAS_GEMM_ALGO9
#define CUBLAS_GEMM_ALGO9_TENSOR_OP HIPBLAS_GEMM_ALGO9_TENSOR_OP
#define CUBLAS_GEMM_DEFAULT HIPBLAS_GEMM_DEFAULT
#define CUBLAS_GEMM_DEFAULT_TENSOR_OP HIPBLAS_GEMM_DEFAULT_TENSOR_OP
#define CUBLAS_GEMM_DFALT HIPBLAS_GEMM_DEFAULT
#define CUBLAS_GEMM_DFALT_TENSOR_OP HIPBLAS_GEMM_DFALT_TENSOR_OP
#define CUBLAS_MATH_DISALLOW_REDUCED_PRECISION_REDUCTION HIPBLAS_MATH_DISALLOW_REDUCED_PRECISION_REDUCTION
#define CUBLAS_OP_C HIPBLAS_OP_C
#define CUBLAS_OP_CONJG HIPBLAS_OP_CONJG
#define CUBLAS_OP_HERMITAN HIPBLAS_OP_C
#define CUBLAS_OP_N HIPBLAS_OP_N
#define CUBLAS_OP_T HIPBLAS_OP_T
#define CUBLAS_PEDANTIC_MATH HIPBLAS_PEDANTIC_MATH
#define CUBLAS_POINTER_MODE_DEVICE HIPBLAS_POINTER_MODE_DEVICE
#define CUBLAS_POINTER_MODE_HOST HIPBLAS_POINTER_MODE_HOST
#define CUBLAS_SIDE_LEFT HIPBLAS_SIDE_LEFT
#define CUBLAS_SIDE_RIGHT HIPBLAS_SIDE_RIGHT
#define CUBLAS_STATUS_ALLOC_FAILED HIPBLAS_STATUS_ALLOC_FAILED
#define CUBLAS_STATUS_ARCH_MISMATCH HIPBLAS_STATUS_ARCH_MISMATCH
#define CUBLAS_STATUS_EXECUTION_FAILED HIPBLAS_STATUS_EXECUTION_FAILED
#define CUBLAS_STATUS_INTERNAL_ERROR HIPBLAS_STATUS_INTERNAL_ERROR
#define CUBLAS_STATUS_INVALID_VALUE HIPBLAS_STATUS_INVALID_VALUE
#define CUBLAS_STATUS_LICENSE_ERROR HIPBLAS_STATUS_LICENSE_ERROR
#define CUBLAS_STATUS_MAPPING_ERROR HIPBLAS_STATUS_MAPPING_ERROR
#define CUBLAS_STATUS_NOT_INITIALIZED HIPBLAS_STATUS_NOT_INITIALIZED
#define CUBLAS_STATUS_NOT_SUPPORTED HIPBLAS_STATUS_NOT_SUPPORTED
#define CUBLAS_STATUS_SUCCESS HIPBLAS_STATUS_SUCCESS
#define CUBLAS_TENSOR_OP_MATH HIPBLAS_TENSOR_OP_MATH
#define CUBLAS_TF32_TENSOR_OP_MATH HIPBLAS_TF32_TENSOR_OP_MATH
#define CUDA_C_16F HIPBLAS_C_16F
#define CUDA_C_32F HIPBLAS_C_32F
#define CUDA_C_32I HIPBLAS_C_32I
#define CUDA_C_32U HIPBLAS_C_32U
#define CUDA_C_64F HIPBLAS_C_64F
#define CUDA_C_8I HIPBLAS_C_8I
#define CUDA_C_8U HIPBLAS_C_8U
#define CUDA_R_16F HIPBLAS_R_16F
#define CUDA_R_32F HIPBLAS_R_32F
#define CUDA_R_32I HIPBLAS_R_32I
#define CUDA_R_32U HIPBLAS_R_32U
#define CUDA_R_64F HIPBLAS_R_64F
#define CUDA_R_8I HIPBLAS_R_8I
#define CUDA_R_8U HIPBLAS_R_8U
#define cublasAlloc hipblasAlloc
#define cublasAsumEx hipblasAsumEx
#define cublasAxpyEx hipblasAxpyEx
#define cublasCaxpy hipblasCaxpy
#define cublasCaxpy_v2 hipblasCaxpy
#define cublasCcopy hipblasCcopy
#define cublasCcopy_v2 hipblasCcopy
#define cublasCdgmm hipblasCdgmm
#define cublasCdotc hipblasCdotc
#define cublasCdotc_v2 hipblasCdotc
#define cublasCdotu hipblasCdotu
#define cublasCdotu_v2 hipblasCdotu
#define cublasCgbmv hipblasCgbmv
#define cublasCgbmv_v2 hipblasCgbmv
#define cublasCgeam hipblasCgeam
#define cublasCgelsBatched hipblasCgelsBatched
#define cublasCgemm hipblasCgemm
#define cublasCgemm3m hipblasCgemm3m
#define cublasCgemm3mBatched hipblasCgemm3mBatched
#define cublasCgemm3mEx hipblasCgemm3mEx
#define cublasCgemm3mStridedBatched hipblasCgemm3mStridedBatched
#define cublasCgemmBatched hipblasCgemmBatched
#define cublasCgemmEx hipblasCgemmEx
#define cublasCgemmStridedBatched hipblasCgemmStridedBatched
#define cublasCgemm_v2 hipblasCgemm
#define cublasCgemv hipblasCgemv
#define cublasCgemv_v2 hipblasCgemv
#define cublasCgeqrfBatched hipblasCgeqrfBatched
#define cublasCgerc hipblasCgerc
#define cublasCgerc_v2 hipblasCgerc
#define cublasCgeru hipblasCgeru
#define cublasCgeru_v2 hipblasCgeru
#define cublasCgetrfBatched hipblasCgetrfBatched
#define cublasCgetriBatched hipblasCgetriBatched
#define cublasCgetrsBatched hipblasCgetrsBatched
#define cublasChbmv hipblasChbmv
#define cublasChbmv_v2 hipblasChbmv
#define cublasChemm hipblasChemm
#define cublasChemm_v2 hipblasChemm
#define cublasChemv hipblasChemv
#define cublasChemv_v2 hipblasChemv
#define cublasCher hipblasCher
#define cublasCher2 hipblasCher2
#define cublasCher2_v2 hipblasCher2
#define cublasCher2k hipblasCher2k
#define cublasCher2k_v2 hipblasCher2k
#define cublasCher_v2 hipblasCher
#define cublasCherk hipblasCherk
#define cublasCherk3mEx hipblasCherk3mEx
#define cublasCherkEx hipblasCherkEx
#define cublasCherk_v2 hipblasCherk
#define cublasCherkx hipblasCherkx
#define cublasChpmv hipblasChpmv
#define cublasChpmv_v2 hipblasChpmv
#define cublasChpr hipblasChpr
#define cublasChpr2 hipblasChpr2
#define cublasChpr2_v2 hipblasChpr2
#define cublasChpr_v2 hipblasChpr
#define cublasCmatinvBatched hipblasCmatinvBatched
#define cublasComputeType_t hipblasComputeType_t
#define cublasCopyEx hipblasCopyEx
#define cublasCreate hipblasCreate
#define cublasCreate_v2 hipblasCreate
#define cublasCrot hipblasCrot
#define cublasCrot_v2 hipblasCrot
#define cublasCrotg hipblasCrotg
#define cublasCrotg_v2 hipblasCrotg
#define cublasCscal hipblasCscal
#define cublasCscal_v2 hipblasCscal
#define cublasCsrot hipblasCsrot
#define cublasCsrot_v2 hipblasCsrot
#define cublasCsscal hipblasCsscal
#define cublasCsscal_v2 hipblasCsscal
#define cublasCswap hipblasCswap
#define cublasCswap_v2 hipblasCswap
#define cublasCsymm hipblasCsymm
#define cublasCsymm_v2 hipblasCsymm
#define cublasCsymv hipblasCsymv
#define cublasCsymv_v2 hipblasCsymv
#define cublasCsyr hipblasCsyr
#define cublasCsyr2 hipblasCsyr2
#define cublasCsyr2_v2 hipblasCsyr2
#define cublasCsyr2k hipblasCsyr2k
#define cublasCsyr2k_v2 hipblasCsyr2k
#define cublasCsyr_v2 hipblasCsyr
#define cublasCsyrk hipblasCsyrk
#define cublasCsyrk3mEx hipblasCsyrk3mEx
#define cublasCsyrkEx hipblasCsyrkEx
#define cublasCsyrk_v2 hipblasCsyrk
#define cublasCsyrkx hipblasCsyrkx
#define cublasCtbmv hipblasCtbmv
#define cublasCtbmv_v2 hipblasCtbmv
#define cublasCtbsv hipblasCtbsv
#define cublasCtbsv_v2 hipblasCtbsv
#define cublasCtpmv hipblasCtpmv
#define cublasCtpmv_v2 hipblasCtpmv
#define cublasCtpsv hipblasCtpsv
#define cublasCtpsv_v2 hipblasCtpsv
#define cublasCtpttr hipblasCtpttr
#define cublasCtrmm hipblasCtrmm
#define cublasCtrmm_v2 hipblasCtrmm
#define cublasCtrmv hipblasCtrmv
#define cublasCtrmv_v2 hipblasCtrmv
#define cublasCtrsm hipblasCtrsm
#define cublasCtrsmBatched hipblasCtrsmBatched
#define cublasCtrsm_v2 hipblasCtrsm
#define cublasCtrsv hipblasCtrsv
#define cublasCtrsv_v2 hipblasCtrsv
#define cublasCtrttp hipblasCtrttp
#define cublasDasum hipblasDasum
#define cublasDasum_v2 hipblasDasum
#define cublasDataType_t hipblasDatatype_t
#define cublasDaxpy hipblasDaxpy
#define cublasDaxpy_v2 hipblasDaxpy
#define cublasDcopy hipblasDcopy
#define cublasDcopy_v2 hipblasDcopy
#define cublasDdgmm hipblasDdgmm
#define cublasDdot hipblasDdot
#define cublasDdot_v2 hipblasDdot
#define cublasDestroy hipblasDestroy
#define cublasDestroy_v2 hipblasDestroy
#define cublasDgbmv hipblasDgbmv
#define cublasDgbmv_v2 hipblasDgbmv
#define cublasDgeam hipblasDgeam
#define cublasDgelsBatched hipblasDgelsBatched
#define cublasDgemm hipblasDgemm
#define cublasDgemmBatched hipblasDgemmBatched
#define cublasDgemmStridedBatched hipblasDgemmStridedBatched
#define cublasDgemm_v2 hipblasDgemm
#define cublasDgemv hipblasDgemv
#define cublasDgemv_v2 hipblasDgemv
#define cublasDgeqrfBatched hipblasDgeqrfBatched
#define cublasDger hipblasDger
#define cublasDger_v2 hipblasDger
#define cublasDgetrfBatched hipblasDgetrfBatched
#define cublasDgetriBatched hipblasDgetriBatched
#define cublasDgetrsBatched hipblasDgetrsBatched
#define cublasDiagType_t hipblasDiagType_t
#define cublasDmatinvBatched hipblasDmatinvBatched
#define cublasDnrm2 hipblasDnrm2
#define cublasDnrm2_v2 hipblasDnrm2
#define cublasDotEx hipblasDotEx
#define cublasDotcEx hipblasDotcEx
#define cublasDrot hipblasDrot
#define cublasDrot_v2 hipblasDrot
#define cublasDrotg hipblasDrotg
#define cublasDrotg_v2 hipblasDrotg
#define cublasDrotm hipblasDrotm
#define cublasDrotm_v2 hipblasDrotm
#define cublasDrotmg hipblasDrotmg
#define cublasDrotmg_v2 hipblasDrotmg
#define cublasDsbmv hipblasDsbmv
#define cublasDsbmv_v2 hipblasDsbmv
#define cublasDscal hipblasDscal
#define cublasDscal_v2 hipblasDscal
#define cublasDspmv hipblasDspmv
#define cublasDspmv_v2 hipblasDspmv
#define cublasDspr hipblasDspr
#define cublasDspr2 hipblasDspr2
#define cublasDspr2_v2 hipblasDspr2
#define cublasDspr_v2 hipblasDspr
#define cublasDswap hipblasDswap
#define cublasDswap_v2 hipblasDswap
#define cublasDsymm hipblasDsymm
#define cublasDsymm_v2 hipblasDsymm
#define cublasDsymv hipblasDsymv
#define cublasDsymv_v2 hipblasDsymv
#define cublasDsyr hipblasDsyr
#define cublasDsyr2 hipblasDsyr2
#define cublasDsyr2_v2 hipblasDsyr2
#define cublasDsyr2k hipblasDsyr2k
#define cublasDsyr2k_v2 hipblasDsyr2k
#define cublasDsyr_v2 hipblasDsyr
#define cublasDsyrk hipblasDsyrk
#define cublasDsyrk_v2 hipblasDsyrk
#define cublasDsyrkx hipblasDsyrkx
#define cublasDtbmv hipblasDtbmv
#define cublasDtbmv_v2 hipblasDtbmv
#define cublasDtbsv hipblasDtbsv
#define cublasDtbsv_v2 hipblasDtbsv
#define cublasDtpmv hipblasDtpmv
#define cublasDtpmv_v2 hipblasDtpmv
#define cublasDtpsv hipblasDtpsv
#define cublasDtpsv_v2 hipblasDtpsv
#define cublasDtpttr hipblasDtpttr
#define cublasDtrmm hipblasDtrmm
#define cublasDtrmm_v2 hipblasDtrmm
#define cublasDtrmv hipblasDtrmv
#define cublasDtrmv_v2 hipblasDtrmv
#define cublasDtrsm hipblasDtrsm
#define cublasDtrsmBatched hipblasDtrsmBatched
#define cublasDtrsm_v2 hipblasDtrsm
#define cublasDtrsv hipblasDtrsv
#define cublasDtrsv_v2 hipblasDtrsv
#define cublasDtrttp hipblasDtrttp
#define cublasDzasum hipblasDzasum
#define cublasDzasum_v2 hipblasDzasum
#define cublasDznrm2 hipblasDznrm2
#define cublasDznrm2_v2 hipblasDznrm2
#define cublasFillMode_t hipblasFillMode_t
#define cublasFree hipblasFree
#define cublasGemmAlgo_t hipblasGemmAlgo_t
#define cublasGemmBatchedEx hipblasGemmBatchedEx
#define cublasGemmEx hipblasGemmEx
#define cublasGemmStridedBatchedEx hipblasGemmStridedBatchedEx
#define cublasGetAtomicsMode hipblasGetAtomicsMode
#define cublasGetCudartVersion hipblasGetCudartVersion
#define cublasGetError hipblasGetError
#define cublasGetLoggerCallback hipblasGetLoggerCallback
#define cublasGetMathMode hipblasGetMathMode
#define cublasGetMatrix hipblasGetMatrix
#define cublasGetMatrixAsync hipblasGetMatrixAsync
#define cublasGetPointerMode hipblasGetPointerMode
#define cublasGetPointerMode_v2 hipblasGetPointerMode
#define cublasGetProperty hipblasGetProperty
#define cublasGetStream hipblasGetStream
#define cublasGetStream_v2 hipblasGetStream
#define cublasGetVector hipblasGetVector
#define cublasGetVectorAsync hipblasGetVectorAsync
#define cublasGetVersion hipblasGetVersion
#define cublasGetVersion_v2 hipblasGetVersion
#define cublasHandle_t hipblasHandle_t
#define cublasHgemm hipblasHgemm
#define cublasHgemmBatched hipblasHgemmBatched
#define cublasHgemmStridedBatched hipblasHgemmStridedBatched
#define cublasIamaxEx hipblasIamaxEx
#define cublasIaminEx hipblasIaminEx
#define cublasIcamax hipblasIcamax
#define cublasIcamax_v2 hipblasIcamax
#define cublasIcamin hipblasIcamin
#define cublasIcamin_v2 hipblasIcamin
#define cublasIdamax hipblasIdamax
#define cublasIdamax_v2 hipblasIdamax
#define cublasIdamin hipblasIdamin
#define cublasIdamin_v2 hipblasIdamin
#define cublasInit hipblasInit
#define cublasIsamax hipblasIsamax
#define cublasIsamax_v2 hipblasIsamax
#define cublasIsamin hipblasIsamin
#define cublasIsamin_v2 hipblasIsamin
#define cublasIzamax hipblasIzamax
#define cublasIzamax_v2 hipblasIzamax
#define cublasIzamin hipblasIzamin
#define cublasIzamin_v2 hipblasIzamin
#define cublasLogCallback hipblasLogCallback
#define cublasLoggerConfigure hipblasLoggerConfigure
#define cublasMath_t hipblasMath_t
#define cublasMigrateComputeType hipblasMigrateComputeType
#define cublasNrm2Ex hipblasNrm2Ex
#define cublasOperation_t hipblasOperation_t
#define cublasPointerMode_t hipblasPointerMode_t
#define cublasRotEx hipblasRotEx
#define cublasRotgEx hipblasRotgEx
#define cublasRotmEx hipblasRotmEx
#define cublasRotmgEx hipblasRotmgEx
#define cublasSasum hipblasSasum
#define cublasSasum_v2 hipblasSasum
#define cublasSaxpy hipblasSaxpy
#define cublasSaxpy_v2 hipblasSaxpy
#define cublasScalEx hipblasScalEx
#define cublasScasum hipblasScasum
#define cublasScasum_v2 hipblasScasum
#define cublasScnrm2 hipblasScnrm2
#define cublasScnrm2_v2 hipblasScnrm2
#define cublasScopy hipblasScopy
#define cublasScopy_v2 hipblasScopy
#define cublasSdgmm hipblasSdgmm
#define cublasSdot hipblasSdot
#define cublasSdot_v2 hipblasSdot
#define cublasSetAtomicsMode hipblasSetAtomicsMode
#define cublasSetKernelStream hipblasSetKernelStream
#define cublasSetLoggerCallback hipblasSetLoggerCallback
#define cublasSetMathMode hipblasSetMathMode
#define cublasSetMatrix hipblasSetMatrix
#define cublasSetMatrixAsync hipblasSetMatrixAsync
#define cublasSetPointerMode hipblasSetPointerMode
#define cublasSetPointerMode_v2 hipblasSetPointerMode
#define cublasSetStream hipblasSetStream
#define cublasSetStream_v2 hipblasSetStream
#define cublasSetVector hipblasSetVector
#define cublasSetVectorAsync hipblasSetVectorAsync
#define cublasSgbmv hipblasSgbmv
#define cublasSgbmv_v2 hipblasSgbmv
#define cublasSgeam hipblasSgeam
#define cublasSgelsBatched hipblasSgelsBatched
#define cublasSgemm hipblasSgemm
#define cublasSgemmBatched hipblasSgemmBatched
#define cublasSgemmEx hipblasSgemmEx
#define cublasSgemmStridedBatched hipblasSgemmStridedBatched
#define cublasSgemm_v2 hipblasSgemm
#define cublasSgemv hipblasSgemv
#define cublasSgemv_v2 hipblasSgemv
#define cublasSgeqrfBatched hipblasSgeqrfBatched
#define cublasSger hipblasSger
#define cublasSger_v2 hipblasSger
#define cublasSgetrfBatched hipblasSgetrfBatched
#define cublasSgetriBatched hipblasSgetriBatched
#define cublasSgetrsBatched hipblasSgetrsBatched
#define cublasShutdown hipblasShutdown
#define cublasSideMode_t hipblasSideMode_t
#define cublasSmatinvBatched hipblasSmatinvBatched
#define cublasSnrm2 hipblasSnrm2
#define cublasSnrm2_v2 hipblasSnrm2
#define cublasSrot hipblasSrot
#define cublasSrot_v2 hipblasSrot
#define cublasSrotg hipblasSrotg
#define cublasSrotg_v2 hipblasSrotg
#define cublasSrotm hipblasSrotm
#define cublasSrotm_v2 hipblasSrotm
#define cublasSrotmg hipblasSrotmg
#define cublasSrotmg_v2 hipblasSrotmg
#define cublasSsbmv hipblasSsbmv
#define cublasSsbmv_v2 hipblasSsbmv
#define cublasSscal hipblasSscal
#define cublasSscal_v2 hipblasSscal
#define cublasSspmv hipblasSspmv
#define cublasSspmv_v2 hipblasSspmv
#define cublasSspr hipblasSspr
#define cublasSspr2 hipblasSspr2
#define cublasSspr2_v2 hipblasSspr2
#define cublasSspr_v2 hipblasSspr
#define cublasSswap hipblasSswap
#define cublasSswap_v2 hipblasSswap
#define cublasSsymm hipblasSsymm
#define cublasSsymm_v2 hipblasSsymm
#define cublasSsymv hipblasSsymv
#define cublasSsymv_v2 hipblasSsymv
#define cublasSsyr hipblasSsyr
#define cublasSsyr2 hipblasSsyr2
#define cublasSsyr2_v2 hipblasSsyr2
#define cublasSsyr2k hipblasSsyr2k
#define cublasSsyr2k_v2 hipblasSsyr2k
#define cublasSsyr_v2 hipblasSsyr
#define cublasSsyrk hipblasSsyrk
#define cublasSsyrk_v2 hipblasSsyrk
#define cublasSsyrkx hipblasSsyrkx
#define cublasStatus hipblasStatus_t
#define cublasStatus_t hipblasStatus_t
#define cublasStbmv hipblasStbmv
#define cublasStbmv_v2 hipblasStbmv
#define cublasStbsv hipblasStbsv
#define cublasStbsv_v2 hipblasStbsv
#define cublasStpmv hipblasStpmv
#define cublasStpmv_v2 hipblasStpmv
#define cublasStpsv hipblasStpsv
#define cublasStpsv_v2 hipblasStpsv
#define cublasStpttr hipblasStpttr
#define cublasStrmm hipblasStrmm
#define cublasStrmm_v2 hipblasStrmm
#define cublasStrmv hipblasStrmv
#define cublasStrmv_v2 hipblasStrmv
#define cublasStrsm hipblasStrsm
#define cublasStrsmBatched hipblasStrsmBatched
#define cublasStrsm_v2 hipblasStrsm
#define cublasStrsv hipblasStrsv
#define cublasStrsv_v2 hipblasStrsv
#define cublasStrttp hipblasStrttp
#define cublasSwapEx hipblasSwapEx
#define cublasUint8gemmBias hipblasUint8gemmBias
#define cublasXerbla hipblasXerbla
#define cublasZaxpy hipblasZaxpy
#define cublasZaxpy_v2 hipblasZaxpy
#define cublasZcopy hipblasZcopy
#define cublasZcopy_v2 hipblasZcopy
#define cublasZdgmm hipblasZdgmm
#define cublasZdotc hipblasZdotc
#define cublasZdotc_v2 hipblasZdotc
#define cublasZdotu hipblasZdotu
#define cublasZdotu_v2 hipblasZdotu
#define cublasZdrot hipblasZdrot
#define cublasZdrot_v2 hipblasZdrot
#define cublasZdscal hipblasZdscal
#define cublasZdscal_v2 hipblasZdscal
#define cublasZgbmv hipblasZgbmv
#define cublasZgbmv_v2 hipblasZgbmv
#define cublasZgeam hipblasZgeam
#define cublasZgelsBatched hipblasZgelsBatched
#define cublasZgemm hipblasZgemm
#define cublasZgemm3m hipblasZgemm3m
#define cublasZgemmBatched hipblasZgemmBatched
#define cublasZgemmStridedBatched hipblasZgemmStridedBatched
#define cublasZgemm_v2 hipblasZgemm
#define cublasZgemv hipblasZgemv
#define cublasZgemv_v2 hipblasZgemv
#define cublasZgeqrfBatched hipblasZgeqrfBatched
#define cublasZgerc hipblasZgerc
#define cublasZgerc_v2 hipblasZgerc
#define cublasZgeru hipblasZgeru
#define cublasZgeru_v2 hipblasZgeru
#define cublasZgetrfBatched hipblasZgetrfBatched
#define cublasZgetriBatched hipblasZgetriBatched
#define cublasZgetrsBatched hipblasZgetrsBatched
#define cublasZhbmv hipblasZhbmv
#define cublasZhbmv_v2 hipblasZhbmv
#define cublasZhemm hipblasZhemm
#define cublasZhemm_v2 hipblasZhemm
#define cublasZhemv hipblasZhemv
#define cublasZhemv_v2 hipblasZhemv
#define cublasZher hipblasZher
#define cublasZher2 hipblasZher2
#define cublasZher2_v2 hipblasZher2
#define cublasZher2k hipblasZher2k
#define cublasZher2k_v2 hipblasZher2k
#define cublasZher_v2 hipblasZher
#define cublasZherk hipblasZherk
#define cublasZherk_v2 hipblasZherk
#define cublasZherkx hipblasZherkx
#define cublasZhpmv hipblasZhpmv
#define cublasZhpmv_v2 hipblasZhpmv
#define cublasZhpr hipblasZhpr
#define cublasZhpr2 hipblasZhpr2
#define cublasZhpr2_v2 hipblasZhpr2
#define cublasZhpr_v2 hipblasZhpr
#define cublasZmatinvBatched hipblasZmatinvBatched
#define cublasZrot hipblasZrot
#define cublasZrot_v2 hipblasZrot
#define cublasZrotg hipblasZrotg
#define cublasZrotg_v2 hipblasZrotg
#define cublasZscal hipblasZscal
#define cublasZscal_v2 hipblasZscal
#define cublasZswap hipblasZswap
#define cublasZswap_v2 hipblasZswap
#define cublasZsymm hipblasZsymm
#define cublasZsymm_v2 hipblasZsymm
#define cublasZsymv hipblasZsymv
#define cublasZsymv_v2 hipblasZsymv
#define cublasZsyr hipblasZsyr
#define cublasZsyr2 hipblasZsyr2
#define cublasZsyr2_v2 hipblasZsyr2
#define cublasZsyr2k hipblasZsyr2k
#define cublasZsyr2k_v2 hipblasZsyr2k
#define cublasZsyr_v2 hipblasZsyr
#define cublasZsyrk hipblasZsyrk
#define cublasZsyrk_v2 hipblasZsyrk
#define cublasZsyrkx hipblasZsyrkx
#define cublasZtbmv hipblasZtbmv
#define cublasZtbmv_v2 hipblasZtbmv
#define cublasZtbsv hipblasZtbsv
#define cublasZtbsv_v2 hipblasZtbsv
#define cublasZtpmv hipblasZtpmv
#define cublasZtpmv_v2 hipblasZtpmv
#define cublasZtpsv hipblasZtpsv
#define cublasZtpsv_v2 hipblasZtpsv
#define cublasZtpttr hipblasZtpttr
#define cublasZtrmm hipblasZtrmm
#define cublasZtrmm_v2 hipblasZtrmm
#define cublasZtrmv hipblasZtrmv
#define cublasZtrmv_v2 hipblasZtrmv
#define cublasZtrsm hipblasZtrsm
#define cublasZtrsmBatched hipblasZtrsmBatched
#define cublasZtrsm_v2 hipblasZtrsm
#define cublasZtrsv hipblasZtrsv
#define cublasZtrsv_v2 hipblasZtrsv
#define cublasZtrttp hipblasZtrttp
#define cudaDataType hipblasDatatype_t
#define cudaDataType_t hipblasDatatype_t
