#pragma once
#include <hipfft.h>
#define CUFFT_ALLOC_FAILED HIPFFT_ALLOC_FAILED
#define CUFFT_C2C HIPFFT_C2C
#define CUFFT_C2R HIPFFT_C2R
#define CUFFT_D2Z HIPFFT_D2Z
#define CUFFT_EXEC_FAILED HIPFFT_EXEC_FAILED
#define CUFFT_FORWARD HIPFFT_FORWARD
#define CUFFT_INCOMPLETE_PARAMETER_LIST HIPFFT_INCOMPLETE_PARAMETER_LIST
#define CUFFT_INTERNAL_ERROR HIPFFT_INTERNAL_ERROR
#define CUFFT_INVALID_DEVICE HIPFFT_INVALID_DEVICE
#define CUFFT_INVALID_PLAN HIPFFT_INVALID_PLAN
#define CUFFT_INVALID_SIZE HIPFFT_INVALID_SIZE
#define CUFFT_INVALID_TYPE HIPFFT_INVALID_TYPE
#define CUFFT_INVALID_VALUE HIPFFT_INVALID_VALUE
#define CUFFT_INVERSE HIPFFT_BACKWARD
#define CUFFT_NOT_IMPLEMENTED HIPFFT_NOT_IMPLEMENTED
#define CUFFT_NOT_SUPPORTED HIPFFT_NOT_SUPPORTED
#define CUFFT_NO_WORKSPACE HIPFFT_NO_WORKSPACE
#define CUFFT_PARSE_ERROR HIPFFT_PARSE_ERROR
#define CUFFT_R2C HIPFFT_R2C
#define CUFFT_SETUP_FAILED HIPFFT_SETUP_FAILED
#define CUFFT_SUCCESS HIPFFT_SUCCESS
#define CUFFT_UNALIGNED_DATA HIPFFT_UNALIGNED_DATA
#define CUFFT_Z2D HIPFFT_Z2D
#define CUFFT_Z2Z HIPFFT_Z2Z
#define cufftComplex hipfftComplex
#define cufftCreate hipfftCreate
#define cufftDestroy hipfftDestroy
#define cufftDoubleComplex hipfftDoubleComplex
#define cufftDoubleReal hipfftDoubleReal
#define cufftEstimate1d hipfftEstimate1d
#define cufftEstimate2d hipfftEstimate2d
#define cufftEstimate3d hipfftEstimate3d
#define cufftEstimateMany hipfftEstimateMany
#define cufftExecC2C hipfftExecC2C
#define cufftExecC2R hipfftExecC2R
#define cufftExecD2Z hipfftExecD2Z
#define cufftExecR2C hipfftExecR2C
#define cufftExecZ2D hipfftExecZ2D
#define cufftExecZ2Z hipfftExecZ2Z
#define cufftGetProperty hipfftGetProperty
#define cufftGetSize hipfftGetSize
#define cufftGetSize1d hipfftGetSize1d
#define cufftGetSize2d hipfftGetSize2d
#define cufftGetSize3d hipfftGetSize3d
#define cufftGetSizeMany hipfftGetSizeMany
#define cufftGetSizeMany64 hipfftGetSizeMany64
#define cufftGetVersion hipfftGetVersion
#define cufftHandle hipfftHandle
#define cufftMakePlan1d hipfftMakePlan1d
#define cufftMakePlan2d hipfftMakePlan2d
#define cufftMakePlan3d hipfftMakePlan3d
#define cufftMakePlanMany hipfftMakePlanMany
#define cufftMakePlanMany64 hipfftMakePlanMany64
#define cufftPlan1d hipfftPlan1d
#define cufftPlan2d hipfftPlan2d
#define cufftPlan3d hipfftPlan3d
#define cufftPlanMany hipfftPlanMany
#define cufftReal hipfftReal
#define cufftResult hipfftResult
#define cufftResult_t hipfftResult_t
#define cufftSetAutoAllocation hipfftSetAutoAllocation
#define cufftSetStream hipfftSetStream
#define cufftSetWorkArea hipfftSetWorkArea
#define cufftType hipfftType
#define cufftType_t hipfftType_t
